apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digit
    demo: "true"
  name: digit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit
  template:
    metadata:
      labels:
        app: digit
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - image: stugee/digit:0.1
        name: digit
        ports:
        - containerPort: 5000
      restartPolicy: Always
