apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load
  name: load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - image: stugee/load:0.1
        name: load
      restartPolicy: Always
